/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.JsonNode;
import com.mashape.unirest.http.Unirest;
import com.mashape.unirest.http.exceptions.UnirestException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws UnirestException {

        HttpResponse<JsonNode> response = Unirest.get("https://gkArenas.atlassian.net/rest/api/3/dashboard")
                .basicAuth("email@example.com", "ATATT3xFfGF0aQkJLWMUrmj0qQtghcd9g3o0a6JsN8sj")
                .header("Accept", "application/json")
                .asJson();

        System.out.println(response.getBody());
    }
}
